services:
  postgres:
    ports:
      - "${DB_PORT:-5432}:5432"

  bot:
    image: music-tool-bot:dev
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      - START_CMD=python -m jurigged -v bot.py
    volumes:
      - ./:/app
      - ./data:/data
      - ./.env:/app/.env:ro
